In [23]:
from datasets import load_dataset

# Load the English dataset from the latest dump
ds_wiki = load_dataset("omarkamali/wikipedia-monthly", "20250703.tr", split="train")
ds_wiki

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Dataset({
    features: ['id', 'url', 'title', 'raw_mediawiki', 'text'],
    num_rows: 641443
})

In [26]:
# first 100 to text with title
text = ""
for i in range(100):
    text += ds_wiki[i]["title"] + "\n" + ds_wiki[i]["text"] + "\n"

while "\n " in text:
    text = text.replace("\n ", "\n")

while "\n\n" in text:
    text = text.replace("\n\n", "\n")


with open("data.txt", "w", encoding="utf-8") as f:
    f.write(text)

print(len(text))

1394660


In [6]:
%pip install turkish-tokenizer -U


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Note: you may need to restart the kernel to use updated packages.


In [1]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-270m-it")


In [2]:
model = AutoModelForCausalLM.from_pretrained("google/gemma-3-270m-it")


In [2]:
from gemma_model import GemmaForCausalLM, get_config_for_270m

config_270m = get_config_for_270m("float32")

gemma_model = GemmaForCausalLM(config_270m, tokenizer)
# gemma_model.load_weights_from_hf(model.model.state_dict())
gemma_model.from_pretrained("gemma-3-270m-hf-it")


Model loaded from gemma-3-270m-hf-it


In [1]:
prompt = "Merhaba, nasılsın?"

In [ ]:
gemma_model.generate(prompt)


' Bugün ne yaptın?\n\n**Merhaba!**\n\n**Neden?**\n\n"Merhaba, nasılsın?"\n\nBu, birçok farklı alanda (aile, arkadaşlıklar, iş, vb.) kullanımıyla ilişkilendirilebilir. Bu ifade, "Merhaba" kelimesiyle ilgili bir farklılık veya kelime farkındalığı duygusunu ifade eder.\n\n**Ne yazılabilir?**\n\nBu ifade, "Merhaba" kelimesiyle ilgili bir farklılık veya'

In [4]:
gemma_model.save_pretrained("gemma-3-270m-hf-it")

Model saved to gemma-3-270m-hf-it


In [2]:
from turkish_tokenizer import TurkishTokenizer

# Tokenizer'ı başlat
tr_tokenizer = TurkishTokenizer()

# Metin tokenizasyonu
text = """
Ali Ata Bak▁ aliler ahmetler selmanlar da bizde onlar da testte kitapta kitabını okudum bu işe
 
 burnunu sokma
Burun buruna bir kaza\toldu
 """
tokens = tr_tokenizer.encode(text)
print("Token IDs:", tokens)

# Token'ları metne geri çevir
decoded_text = tr_tokenizer.decode(tokens)
print("Decoded:", decoded_text)

Token IDs: [3, 0, 2697, 2, 0, 2212, 2, 0, 2794, 1, 2, 18194, 20043, 2, 6766, 20000, 2, 17321, 20000, 2, 20024, 2, 2595, 20024, 2, 2627, 2, 20024, 2, 3045, 20024, 2, 227, 20024, 2, 227, 15247, 2, 2656, 10572, 2, 2503, 2, 2599, 20038, 3, 3, 2, 165, 20021, 20035, 2, 20064, 4373, 20002, 3, 0, 165, 2, 165, 20037, 2, 2501, 2, 3303, 4, 2502, 20026, 3, 2]
Decoded: 
Ali Ata Bak▁u▁ aliler ahmetler selmanlar da bizde onlar da testte kitapta kitabını okudum bu işe

 burnunu sokma
Burun burna bir kaza	oldu
 


In [3]:
from gemma_model import GemmaForCausalLM, get_config_for_270m_tr_tokenizer
import torch
# Automatic device detection
device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"

config_270m = get_config_for_270m_tr_tokenizer("float32")

gemma_model = GemmaForCausalLM(config_270m, tr_tokenizer, device)
# gemma_model.load_weights_from_hf(model.model.state_dict())
gemma_model.from_pretrained("gemma-3-270m-tr-tokenizer-it")


Model loaded from gemma-3-270m-tr-tokenizer-it


In [ ]:
gemma_model

In [4]:

# Generate text (no device parameter needed)
response = gemma_model.generate(
    prompts="Hello, how are you?",
    output_len=50,
    temperature=0.7
)

In [6]:
response

'ek_temp_20212ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244ek_temp_20244'

In [5]:
gemma_model.generate(prompt)


'ek_temp_20200ek_temp_20084ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_200

In [11]:
import torch

gemma_model.embedder(torch.tensor([157]).to(gemma_model.device))[:,:15]

tensor([[ 0.4416,  0.9512,  1.0129, -0.0926, -0.5219, -1.2538, -0.1451, -1.1735,
          1.4885, -0.5281,  1.1859, -0.0598,  0.4107,  1.3094,  0.4045]],
       device='mps:0', grad_fn=<SliceBackward0>)

In [53]:
gemma_model.embedder.weight.shape

torch.Size([32768, 640])

In [18]:
model.model.embed_tokens(torch.tensor([30158]))[:,:15]

tensor([[ 0.4416,  0.9512,  1.0129, -0.0926, -0.5219, -1.2538, -0.1451, -1.1735,
          1.4885, -0.5281,  1.1859, -0.0598,  0.4107,  1.3094,  0.4045]],
       grad_fn=<SliceBackward0>)

In [11]:
model.model.layers[4].mlp.gate_proj.weight[234][:15], gemma_model.model.layers[4].mlp.gate_proj.weight[234][:15]

(tensor([ 0.0264, -0.0087,  0.0054,  0.0137, -0.0089,  0.0084,  0.0043, -0.0322,
          0.0408,  0.0034, -0.0100,  0.0056, -0.0010,  0.0203, -0.0325],
        grad_fn=<SliceBackward0>),
 tensor([ 0.0264, -0.0087,  0.0054,  0.0137, -0.0089,  0.0084,  0.0043, -0.0322,
          0.0408,  0.0034, -0.0100,  0.0056, -0.0010,  0.0203, -0.0325],
        grad_fn=<SliceBackward0>))

In [14]:
gemma_model.save_pretrained("gemma-3-270m-tr-tokenizer-it")

Model saved to gemma-3-270m-tr-tokenizer-it


In [ ]:
import torch
tensors = tokenizer.encode(prompt)
tensors = torch.tensor(tensors)
tensors = tensors.unsqueeze(0)
tensors = tensors.to("cpu")

ids = model.generate(tensors)
ids

In [ ]:
tokenizer.decode(ids[0])

In [ ]:
model_1b = AutoModelForCausalLM.from_pretrained("google/gemma-3-1b-pt")
model_1b

In [ ]:
all_tr_tokens = tr_tokenizer.get_vocab()

print(len(all_tr_tokens))
print(len(tr_tokenizer.reverse_dict))
print(tr_tokenizer.vocab_size)

In [ ]:
all_tr_tokens["ali"]

In [12]:
from tokenizer_matcher import TokenizerMatcher


tokenizer_matcher = TokenizerMatcher(tokenizer, tr_tokenizer, model, gemma_model)
matched_embeddings = tokenizer_matcher.match_embeddings()

tokenizer_matcher.change_target_model_embeddings(matched_embeddings)

gemma_model.generate(prompt)

Changed 32763 embeddings out of 32763 matched tokens


'ek_temp_20200ek_temp_20084ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20074ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_20077ek_temp_200

In [36]:
matched_tokens = tokenizer_matcher.match_tokens()
matched_tokens[157]


[2, 30158]

In [37]:
tokenizer.vocab_size

262144

In [ ]:
token = "soğucuk"
ids = tokenizer.encode(token)
tr_ids = tr_tokenizer.encode(token)

print(ids)
print(tr_ids)

print(tokenizer.tokenize(token))
print(tr_tokenizer.tokenize(token))
print(tr_tokenizer.decode(tr_ids))

In [ ]:
example_ids = [157, 165, 5]


In [ ]:
tokenizer.eos_token_id

In [ ]:
model.model.state_dict().keys()


In [42]:
model.model.embed_tokens.weight[30158][:15]

tensor([ 0.0175,  0.0376,  0.0400, -0.0037, -0.0206, -0.0496, -0.0057, -0.0464,
         0.0588, -0.0209,  0.0469, -0.0024,  0.0162,  0.0518,  0.0160],
       grad_fn=<SliceBackward0>)

In [44]:
model.lm_head.weight[30158][:15]

tensor([ 0.0175,  0.0376,  0.0400, -0.0037, -0.0206, -0.0496, -0.0057, -0.0464,
         0.0588, -0.0209,  0.0469, -0.0024,  0.0162,  0.0518,  0.0160],
       grad_fn=<SliceBackward0>)